### ISSUE TITLE
下载失败，提示错误如下，在armbian 运行 PHP 7.0.33-0+deb9u2 (cli)

### ISSUE THREAD

**Issue by ronsongg** [zzjzz9266a/91porn_php#12]
http://91porn.com/view_video.php?viewkey=0ae3a2c4115b42b30eae&page=1&viewtype=basic&category=top
PHP Warning:  file_get_contents(http://91porn.com/view_video.php?viewkey=0ae3a2c4115b42b30eae&page=1&viewtype=basic&category=top): failed to open stream: Connection timed out in /root/91/vendor/imangazaliev/didom/src/DiDom/Document.php on line 349
RuntimeException: Could not load file http://91porn.com/view_video.php?viewkey=0ae3a2c4115b42b30eae&page=1&viewtype=basic&category=top in /root/91/vendor/imangazaliev/didom/src/DiDom/Document.php:358
Stack trace:
#0 /root/91/vendor/imangazaliev/didom/src/DiDom/Document.php(241): DiDom\Document->loadFile('http://91porn.c...')
#1 /root/91/vendor/imangazaliev/didom/src/DiDom/Document.php(69): DiDom\Document->load('http://91porn.c...', true, 'html')
#2 /root/91/detailPage.php(9): DiDom\Document->__construct('http://91porn.c...', true, 'Accept-Language...')
#3 /root/91/91all.php(26): singlePage('http://91porn.c...', '\xE6\xB1\x82\xE6\xB1\x82\xE4\xBD\xA0\xEF\xBC\x8C\xE6\x8A\x8A...')
#4 /root/91/91all.php(37): listPage('http://91porn.c...')
#5 {main}

主路由开了全局

**Comment by zzjzz9266a** [comment]
最近两会期间所有翻墙都挂了，我也好几天没下到视频了

**Comment by ronsongg** [comment]
所以这个错误是网的问题不是我环境问题吗

**Comment by zzjzz9266a** [comment]
我觉得是的

**Comment by zzjzz9266a** [comment]
我认为是的，issue里面很多都是网络问题，而且这个库也不需要什么环境，只要能运行php的地方就行
