### ISSUE TITLE
1.0版本运行报错

### ISSUE THREAD

**Issue by jiutianjuju** [zzjzz9266a/91porn_php#20]
运行环境：centos6.4
报错信息
PHP Notice:  Undefined offset: 0 in /91porn_php-1.0.0/91porn_php-1.0.0/detailPage.php on line 11
PHP Fatal error:  Call to a member function getAttribute() on a non-object in /91porn_php-1.0.0/91porn_php-1.0.0/detailPage.php on line 11

**Comment by jiutianjuju** [comment]
php版本是5.4.16，不知道是不是php版本问题

**Comment by jiutianjuju** [comment]
更换php7.2
运行报错：
Uncaught Error: Call to a member function getAttribute() on null in /91porn_php-1.0.0/91porn_php-1.0.0/detailPage.php:11
Stack trace:
#0 /91porn_php-1.0.0/91porn_php-1.0.0/91all.php(37): singlePage('http://91porn.c...', '\xE9\x9C\xB2\xE8\x84\xB8\xE5\xB0\x91\xE5\xA6\x87 \xE5\xBE...')
#1 /91porn_php-1.0.0/91porn_php-1.0.0/91all.php(48): listPage('http://91porn.c...')
#2 {main}
  thrown in /91porn_php-1.0.0/91porn_php-1.0.0/detailPage.php on line 11

**Comment by LLLLFu** [comment]
php >= 5.6

**Comment by zzjzz9266a** [comment]
其实5.4应该也问题不大，你这个应该是没获取到数据， 搞搞翻墙吧骚年

**Comment by jiutianjuju** [comment]
> 其实5.4应该也问题不大，你这个应该是没获取到数据，搞搞翻墙吧骚年

香港地域的ECS，用v2.0下载没问题，升了内存，但是v2.0在执行91all.php时，本地最热类目不会报错，收藏最多类目下载到第五个文件时会报错上述类似的错误

**Comment by zzjzz9266a** [comment]
我明白了，有的视频没有分享链接，所以还是需要依赖nodejs，只需要安装好nodejs，把项目切到nodejs分支就可以
