### ISSUE TITLE
提示这个错误帮忙看看是啥问题

### ISSUE THREAD

**Issue by ronsongg** [zzjzz9266a/91porn_php#25]
http://91porn.com/v.php?category=top&viewtype=basic&page=1
InvalidArgumentException: DiDom\Document::load expects parameter 1 to be string, boolean given in /root/91porn_php/vendor/imangazaliev/didom/src/DiDom/Document.php:218
Stack trace:
#0 /root/91porn_php/vendor/imangazaliev/didom/src/DiDom/Document.php(69): DiDom\Document->load(false, false, 'html')
#1 /root/91porn_php/91all.php(18): DiDom\Document->__construct(false)
#2 /root/91porn_php/91all.php(37): listPage('http://91porn.c...')
#3 {main}

这个也是网络问题吗。我路由器全局翻的环境

**Comment by flyfire2003** [comment]
> 
> 
> http://91porn.com/v.php?category=top&viewtype=basic&page=1
> InvalidArgumentException: DiDom\Document::load expects parameter 1 to be string, boolean given in /root/91porn_php/vendor/imangazaliev/didom/src/DiDom/Document.php:218
> Stack trace:
> #0 /root/91porn_php/vendor/imangazaliev/didom/src/DiDom/Document.php(69): DiDom\Document->load(false, false, 'html')
> #1 /root/91porn_php/91all.php(18): DiDom\Document->__construct(false)
> #2 /root/91porn_php/91all.php(37): listPage('http://91porn.c...')
> #3 {main}
> 
> 这个也是网络问题吗。我路由器全局翻的环境

我也是这个问题，我也是路由全局翻，有解决嘛？

**Comment by flyfire2003** [comment]
> > http://91porn.com/v.php?category=top&viewtype=basic&page=1
> > InvalidArgumentException: DiDom\Document::load expects parameter 1 to be string, boolean given in /root/91porn_php/vendor/imangazaliev/didom/src/DiDom/Document.php:218
> > Stack trace:
> > #0 /root/91porn_php/vendor/imangazaliev/didom/src/DiDom/Document.php(69): DiDom\Document->load(false, false, 'html')
> > #1 /root/91porn_php/91all.php(18): DiDom\Document->__construct(false)
> > #2 /root/91porn_php/91all.php(37): listPage('http://91porn.c...')
> > #3 {main}
> > 这个也是网络问题吗。我路由器全局翻的环境
> 
> 我也是这个问题，我也是路由全局翻，有解决嘛？

已经解决了，是网络不通的问题，如果有相同情况的，请检查你的网络
