### ISSUE TITLE
报错Fatal error

### ISSUE THREAD

**Issue by fel835** [zzjzz9266a/91porn_php#31]
Fatal error: Uncaught InvalidArgumentException: DiDom\Document::load expects parameter 1 to be string, boolean given in /root/91porn/vendor/imangazaliev/didom/src/DiDom/Document.php:218
Stack trace:
#0 /root/91porn/vendor/imangazaliev/didom/src/DiDom/Document.php(69): DiDom\Document->load(false, false, 'html')
#1 /root/91porn/91porn.php(12): DiDom\Document->__construct(false)
#2 /root/91porn/91porn.php(24): listPage()
#3 {main}
  thrown in /root/91porn/vendor/imangazaliev/didom/src/DiDom/Document.php on line 218

**Comment by hyc-cc** [comment]
我也是这个报错，你解决了吗？
