### ISSUE TITLE
大哥！新出现的问题，为什么aria2里面有些可以下载，大多数视频下载失败嘞~

### ISSUE THREAD

**Issue by DeeWin1228** [zzjzz9266a/91porn_php#44]

**Comment by zzjzz9266a** [comment]
你不用代理的话aria2的稳定性还不如直接下

**Comment by DeeWin1228** [comment]
> 你不用代理的话aria2的稳定性还不如php命令行直接下

大佬，问题出现了。 aria2的代理在哪里添加哦。我安装了ss-privoxy 把这个容器的8118端口映射到了群晖上，群晖可以添加http代理 并且可以访问谷歌了，说明这里设置是正确de ;
我看到容器的ip是127.17.0.4 群晖docker0网卡的ip127.17.0.1  这两个是互通的。  然后我追加了两行到aria2.conf里面，分别是http-proxy=127.17.0.1：8118和https-proxy=127.17.0.1:8118 
这样子还是不行哦，请问aria2的代理怎么设置哦

**Comment by usbcdrom** [comment]
大佬请看看我这是哪里出了问题，目前我Aria2和和直接那个php都用不了
[root@localhost home]# git clone -b aria2 git@github.com:zzjzz9266a/91porn_php.git
Cloning into '91porn_php'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
[root@localhost home]# git clone https://github.com/zzjzz9266a/91porn_php
Cloning into '91porn_php'...
remote: Enumerating objects: 38, done.
remote: Counting objects: 100% (38/38), done.
remote: Compressing objects: 100% (28/28), done.
remote: Total 319 (delta 21), reused 20 (delta 10), pack-reused 281
Receiving objects: 100% (319/319), 589.38 KiB | 338.00 KiB/s, done.
Resolving deltas: 100% (142/142), done.
[root@localhost home]# git clone -b aria2 https://github.com/zzjzz9266a/91porn_php
Cloning into '91porn_php'...
remote: Enumerating objects: 38, done.
remote: Counting objects: 100% (38/38), done.
remote: Compressing objects: 100% (28/28), done.
remote: Total 319 (delta 21), reused 20 (delta 10), pack-reused 281
Receiving objects: 100% (319/319), 589.38 KiB | 273.00 KiB/s, done.
Resolving deltas: 100% (142/142), done.
[root@localhost home]# cd /home/91porn_php
[root@localhost 91porn_php]# 91all.php
bash: 91all.php: command not found...
[root@localhost 91porn_php]#

**Comment by usbcdrom** [comment]
上面的事aria2这个事PHP
[root@localhost home]# git clone https://github.com/zzjzz9266a/91porn_php
Cloning into '91porn_php'...
remote: Enumerating objects: 38, done.
remote: Counting objects: 100% (38/38), done.
remote: Compressing objects: 100% (28/28), done.
remote: Total 319 (delta 21), reused 20 (delta 10), pack-reused 281
Receiving objects: 100% (319/319), 589.38 KiB | 282.00 KiB/s, done.
Resolving deltas: 100% (142/142), done.
[root@localhost home]# cd /home/91porn_php
[root@localhost 91porn_php]# 91all.php
bash: 91all.php: command not found...
[root@localhost 91porn_php]# php 91all.php

http://91porn.com/v.php?category=top&viewtype=basic&page=1
InvalidArgumentException: DiDom\Document::load expects parameter 1 to be string, boolean given in /home/91porn_php/vendor/imangazaliev/didom/src/DiDom/Document.php:218
Stack trace:
#0 /home/91porn_php/vendor/imangazaliev/didom/src/DiDom/Document.php(69): DiDom\Document->load(false, false, 'html')
#1 /home/91porn_php/91all.php(15): DiDom\Document->__construct(false)
#2 /home/91porn_php/91all.php(35): listPage('http://91porn.c...', 1, 10)
#3 {main}
http://91porn.com/v.php?category=top&viewtype=basic&page=2
InvalidArgumentException: DiDom\Document::load expects parameter 1 to be string, boolean given in /home/91porn_php/vendor/imangazaliev/didom/src/DiDom/Document.php:218
Stack trace:
#0 /home/91porn_php/vendor/imangazaliev/didom/src/DiDom/Document.php(69): DiDom\Document->load(false, false, 'html')
#1 /home/91porn_php/91all.php(15): DiDom\Document->__construct(false)
#2 /home/91porn_php/91all.php(35): listPage('http://91porn.c...', 1, 10)
#3 {main}
http://91porn.com/v.php?category=top&viewtype=basic&page=3
InvalidArgumentException: DiDom\Document::load expects parameter 1 to be string, boolean given in /home/91porn_php/vendor/imangazaliev/didom/src/DiDom/Document.php:218
Stack trace:
#0 /home/91porn_php/vendor/imangazaliev/didom/src/DiDom/Document.php(69): DiDom\Document->load(false, false, 'html')
#1 /home/91porn_php/91all.php(15): DiDom\Document->__construct(false)
#2 /home/91porn_php/91all.php(35): listPage('http://91porn.c...', 1, 10)
#3 {main}
http://91porn.com/v.php?category=top&viewtype=basic&page=4
InvalidArgumentException: DiDom\Document::load expects parameter 1 to be string, boolean given in /home/91porn_php/vendor/imangazaliev/didom/src/DiDom/Document.php:218
Stack trace:
#0 /home/91porn_php/vendor/imangazaliev/didom/src/DiDom/Document.php(69): DiDom\Document->load(false, false, 'html')
#1 /home/91porn_php/91all.php(15): DiDom\Document->__construct(false)
#2 /home/91porn_php/91all.php(35): listPage('http://91porn.c...', 1, 10)
#3 {main}
http://91porn.com/v.php?category=top&viewtype=basic&page=5
InvalidArgumentException: DiDom\Document::load expects parameter 1 to be string, boolean given in /home/91porn_php/vendor/imangazaliev/didom/src/DiDom/Document.php:218
Stack trace:
#0 /home/91porn_php/vendor/imangazaliev/didom/src/DiDom/Document.php(69): DiDom\Document->load(false, false, 'html')
#1 /home/91porn_php/91all.php(15): DiDom\Document->__construct(false)
#2 /home/91porn_php/91all.php(35): listPage('http://91porn.c...', 1, 10)
#3 {main}
http://91porn.com/v.php?category=top&viewtype=basic&page=6
InvalidArgumentException: DiDom\Document::load expects parameter 1 to be string, boolean given in /home/91porn_php/vendor/imangazaliev/didom/src/DiDom/Document.php:218
Stack trace:
#0 /home/91porn_php/vendor/imangazaliev/didom/src/DiDom/Document.php(69): DiDom\Document->load(false, false, 'html')
#1 /home/91porn_php/91all.php(15): DiDom\Document->__construct(false)
#2 /home/91porn_php/91all.php(35): listPage('http://91porn.c...', 1, 10)
#3 {main}
http://91porn.com/v.php?category=top&viewtype=basic&page=7
InvalidArgumentException: DiDom\Document::load expects parameter 1 to be string, boolean given in /home/91porn_php/vendor/imangazaliev/didom/src/DiDom/Document.php:218
Stack trace:
#0 /home/91porn_php/vendor/imangazaliev/didom/src/DiDom/Document.php(69): DiDom\Document->load(false, false, 'html')
#1 /home/91porn_php/91all.php(15): DiDom\Document->__construct(false)
#2 /home/91porn_php/91all.php(35): listPage('http://91porn.c...', 1, 10)
#3 {main}
http://91porn.com/v.php?category=top&viewtype=basic&page=8
InvalidArgumentException: DiDom\Document::load expects parameter 1 to be string, boolean given in /home/91porn_php/vendor/imangazaliev/didom/src/DiDom/Document.php:218
Stack trace:
#0 /home/91porn_php/vendor/imangazaliev/didom/src/DiDom/Document.php(69): DiDom\Document->load(false, false, 'html')
#1 /home/91porn_php/91all.php(15): DiDom\Document->__construct(false)
#2 /home/91porn_php/91all.php(35): listPage('http://91porn.c...', 1, 10)
#3 {main}
http://91porn.com/v.php?category=top&viewtype=basic&page=9
InvalidArgumentException: DiDom\Document::load expects parameter 1 to be string, boolean given in /home/91porn_php/vendor/imangazaliev/didom/src/DiDom/Document.php:218
Stack trace:
#0 /home/91porn_php/vendor/imangazaliev/didom/src/DiDom/Document.php(69): DiDom\Document->load(false, false, 'html')
#1 /home/91porn_php/91all.php(15): DiDom\Document->__construct(false)
#2 /home/91porn_php/91all.php(35): listPage('http://91porn.c...', 1, 10)
#3 {main}
http://91porn.com/v.php?category=top&viewtype=basic&page=10
InvalidArgumentException: DiDom\Document::load expects parameter 1 to be string, boolean given in /home/91porn_php/vendor/imangazaliev/didom/src/DiDom/Document.php:218
Stack trace:
#0 /home/91porn_php/vendor/imangazaliev/didom/src/DiDom/Document.php(69): DiDom\Document->load(false, false, 'html')
#1 /home/91porn_php/91all.php(15): DiDom\Document->__construct(false)
#2 /home/91porn_php/91all.php(35): listPage('http://91porn.c...', 1, 10)
#3 {main}
http://91porn.com/v.php?category=mf&viewtype=basic&page=1
InvalidArgumentException: DiDom\Document::load expects parameter 1 to be string, boolean given in /home/91porn_php/vendor/imangazaliev/didom/src/DiDom/Document.php:218
Stack trace:
#0 /home/91porn_php/vendor/imangazaliev/didom/src/DiDom/Document.php(69): DiDom\Document->load(false, false, 'html')
#1 /home/91porn_php/91all.php(15): DiDom\Document->__construct(false)
#2 /home/91porn_php/91all.php(35): listPage('http://91porn.c...', 1, 5)
#3 {main}
http://91porn.com/v.php?category=mf&viewtype=basic&page=2
InvalidArgumentException: DiDom\Document::load expects parameter 1 to be string, boolean given in /home/91porn_php/vendor/imangazaliev/didom/src/DiDom/Document.php:218
Stack trace:
#0 /home/91porn_php/vendor/imangazaliev/didom/src/DiDom/Document.php(69): DiDom\Document->load(false, false, 'html')
#1 /home/91porn_php/91all.php(15): DiDom\Document->__construct(false)
#2 /home/91porn_php/91all.php(35): listPage('http://91porn.c...', 1, 5)
#3 {main}
http://91porn.com/v.php?category=mf&viewtype=basic&page=3
InvalidArgumentException: DiDom\Document::load expects parameter 1 to be string, boolean given in /home/91porn_php/vendor/imangazaliev/didom/src/DiDom/Document.php:218
Stack trace:
#0 /home/91porn_php/vendor/imangazaliev/didom/src/DiDom/Document.php(69): DiDom\Document->load(false, false, 'html')
#1 /home/91porn_php/91all.php(15): DiDom\Document->__construct(false)
#2 /home/91porn_php/91all.php(35): listPage('http://91porn.c...', 1, 5)
#3 {main}
http://91porn.com/v.php?category=mf&viewtype=basic&page=4
InvalidArgumentException: DiDom\Document::load expects parameter 1 to be string, boolean given in /home/91porn_php/vendor/imangazaliev/didom/src/DiDom/Document.php:218
Stack trace:
#0 /home/91porn_php/vendor/imangazaliev/didom/src/DiDom/Document.php(69): DiDom\Document->load(false, false, 'html')
#1 /home/91porn_php/91all.php(15): DiDom\Document->__construct(false)
#2 /home/91porn_php/91all.php(35): listPage('http://91porn.c...', 1, 5)
#3 {main}
http://91porn.com/v.php?category=mf&viewtype=basic&page=5
InvalidArgumentException: DiDom\Document::load expects parameter 1 to be string, boolean given in /home/91porn_php/vendor/imangazaliev/didom/src/DiDom/Document.php:218
Stack trace:
#0 /home/91porn_php/vendor/imangazaliev/didom/src/DiDom/Document.php(69): DiDom\Document->load(false, false, 'html')
#1 /home/91porn_php/91all.php(15): DiDom\Document->__construct(false)
#2 /home/91porn_php/91all.php(35): listPage('http://91porn.c...', 1, 5)
#3 {main}
http://91porn.com/v.php?category=md&viewtype=basic&page=4
InvalidArgumentException: DiDom\Document::load expects parameter 1 to be string, boolean given in /home/91porn_php/vendor/imangazaliev/didom/src/DiDom/Document.php:218
Stack trace:
#0 /home/91porn_php/vendor/imangazaliev/didom/src/DiDom/Document.php(69): DiDom\Document->load(false, false, 'html')
#1 /home/91porn_php/91all.php(15): DiDom\Document->__construct(false)
#2 /home/91porn_php/91all.php(37): listPage('http://91porn.c...', 4, 4)
#3 {main}[root@localhost 91porn_php]#

**Comment by usbcdrom** [comment]
公网IP也换了，我目前在国外，一个月前还能用

**Comment by zzjzz9266a** [comment]
把config.php里的这一行注释掉试试
![image](https://user-images.githubusercontent.com/17211710/64098047-6ed9c780-cd98-11e9-976f-f676f86d9ba2.png)

**Comment by usbcdrom** [comment]
> 把config.php里的这一行注释掉试试
> ![image](https://user-images.githubusercontent.com/17211710/64098047-6ed9c780-cd98-11e9-976f-f676f86d9ba2.png)

大哥看看我的问题吧，我一个月前用你的程序都是正常的，现在不论是PHP还是Aria2都不行啊

**Comment by zzjzz9266a** [comment]
> > 把config.php里的这一行注释掉试试
> > ![image](https://user-images.githubusercontent.com/17211710/64098047-6ed9c780-cd98-11e9-976f-f676f86d9ba2.png)
> 
> 大哥看看我的问题吧，我一个月前用你的程序都是正常的，现在不论是PHP还是Aria2都不行啊

我就是在说你的啊，你更新了没，91这几天页面结构变化很多，我也跟着改了，aira2的我懒得动了，感觉没什么实际意义

**Comment by zzjzz9266a** [comment]
> > 你不用代理的话aria2的稳定性还不如php命令行直接下
> 
> 大佬，问题出现了。 aria2的代理在哪里添加哦。我安装了ss-privoxy 把这个容器的8118端口映射到了群晖上，群晖可以添加http代理 并且可以访问谷歌了，说明这里设置是正确de ;
> 我看到容器的ip是127.17.0.4 群晖docker0网卡的ip127.17.0.1 这两个是互通的。 然后我追加了两行到aria2.conf里面，分别是http-proxy=127.17.0.1：8118和https-proxy=127.17.0.1:8118
> 这样子还是不行哦，请问aria2的代理怎么设置哦

下载最新的master，别用aria2的了

**Comment by usbcdrom** [comment]
> > > 你不用代理的话aria2的稳定性还不如php命令行直接下
> > 
> > 
> > 大佬，问题出现了。 aria2的代理在哪里添加哦。我安装了ss-privoxy 把这个容器的8118端口映射到了群晖上，群晖可以添加http代理 并且可以访问谷歌了，说明这里设置是正确de ;
> > 我看到容器的ip是127.17.0.4 群晖docker0网卡的ip127.17.0.1 这两个是互通的。 然后我追加了两行到aria2.conf里面，分别是http-proxy=127.17.0.1：8118和https-proxy=127.17.0.1:8118
> > 这样子还是不行哦，请问aria2的代理怎么设置哦
> 
> 下载最新的master，别用aria2的了

![QQ截图20190902170035](https://user-images.githubusercontent.com/43695445/64102736-2542aa00-cda3-11e9-9590-fdaf1a6e586d.jpg)
已经可以正常运行了，谢谢大佬

**Comment by DeeWin1228** [comment]
> > > 你不用代理的话aria2的稳定性还不如php命令行直接下
> > 
> > 
> > 大佬，问题出现了。 aria2的代理在哪里添加哦。我安装了ss-privoxy 把这个容器的8118端口映射到了群晖上，群晖可以添加http代理 并且可以访问谷歌了，说明这里设置是正确de ;
> > 我看到容器的ip是127.17.0.4 群晖docker0网卡的ip127.17.0.1 这两个是互通的。 然后我追加了两行到aria2.conf里面，分别是http-proxy=127.17.0.1：8118和https-proxy=127.17.0.1:8118
> > 这样子还是不行哦，请问aria2的代理怎么设置哦
> 
> 下载最新的master，别用aria2的了

**HP Fatal error:  Call to a member function getAttribute() on null in /root/91porn_php/detailPage.php on line 21

Fatal error: Call to a member function getAttribute() on null in /root/91porn_php/detailPage.php on line 21**
root@YanDong-Station:~/91porn_php# php -v
PHP 5.6.11 (cli) (built: Jul  3 2018 21:23:42) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
大佬 请问 这样子报错是哪里的问题哦 我的php 5.6.11
