### ISSUE TITLE
麻烦大佬看看这个报错

### ISSUE THREAD

**Issue by deemoartisan** [zzjzz9266a/91porn_php#54]
PHP Fatal error:  Uncaught Error: Call to undefined function curl_init() in /content/drive/91/php/detailPage.php:52
Stack trace:
#0 /content/drive/91/php/91porn.php(11): getHtml('http://91porn.c...')
#1 /content/drive/91/php/91porn.php(24): listPage()
#2 {main}
  thrown in /content/drive/91/php/detailPage.php on line 52

**Comment by deemoartisan** [comment]
上面那个是porn.php,下面这个是all的，也报错
http://91porn.com/v.php?next=watch&page=2
PHP Fatal error:  Uncaught Error: Call to undefined function curl_init() in /content/drive/91/php/detailPage.php:52
Stack trace:
#0 /content/drive/91/php/91all.php(14): getHtml('http://91porn.c...')
#1 /content/drive/91/php/91all.php(35): listPage('http://91porn.c...', 2, 100)
#2 {main}
  thrown in /content/drive/91/php/detailPage.php on line 52

**Comment by usbcdrom** [comment]
等作者出现

**Comment by zzjzz9266a** [comment]
php的curl扩展没开，谷歌一下如何打开就行
