### ISSUE TITLE
麻烦大佬看下错误提示

### ISSUE THREAD

**Issue by kuckyhappy** [zzjzz9266a/91porn_php#56]
#3 {main}DSM> docker exec -it 91porn php /root/91porn/91all.php
ERRO[0000] Unable to connect to local syslog daemon

http://627.workarea7.live/v.php?category=top&viewtype=basic&page=1

真实搭讪00后女神，只传91
http://627.workarea7.live/view_video.php?viewkey=9cbd30ae2fc3568f679d&page=1&viewtype=basic&category=top
InvalidArgumentException: DiDom\Document::load expects parameter 1 to be string, boolean given in /root/91porn/vendor/imangazaliev/didom/src/DiDom/Document.php:218
Stack trace:
#0 /root/91porn/vendor/imangazaliev/didom/src/DiDom/Document.php(69): DiDom\Document->load(false, false, 'html')
#1 /root/91porn/detailPage.php(24): DiDom\Document->__construct(false)
#2 /root/91porn/91all.php(23): singlePage('http://627.work...', '\xE7\x9C\x9F\xE5\xAE\x9E\xE6\x90\xAD\xE8\xAE\xAA00\xE5...')
#3 /root/91porn/91all.php(35): listPage('http://627.work...', 1, 10)
#4 {main}
http://627.workarea7.live/v.php?category=top&viewtype=basic&page=2
InvalidArgumentException: DiDom\Document::load expects parameter 1 to be string, boolean given in /root/91porn/vendor/imangazaliev/didom/src/DiDom/Document.php:218
Stack trace:
#0 /root/91porn/vendor/imangazaliev/didom/src/DiDom/Document.php(69): DiDom\Document->load(false, false, 'html')
#1 /root/91porn/91all.php(15): DiDom\Document->__construct(false)
#2 /root/91porn/91all.php(35): listPage('http://627.work...', 1, 10)
#3 {main}
http://627.workarea7.live/v.php?category=top&viewtype=basic&page=3
InvalidArgumentException: DiDom\Document::load expects parameter 1 to be string, boolean given in /root/91porn/vendor/imangazaliev/didom/src/DiDom/Document.php:218
Stack trace:
#0 /root/91porn/vendor/imangazaliev/didom/src/DiDom/Document.php(69): DiDom\Document->load(false, false, 'html')
#1 /root/91porn/91all.php(15): DiDom\Document->__construct(false)
#2 /root/91porn/91all.php(35): listPage('http://627.work...', 1, 10)
#3 {main}
http://627.workarea7.live/v.php?category=top&viewtype=basic&page=4
InvalidArgumentException: DiDom\Document::load expects parameter 1 to be string, boolean given in /root/91porn/vendor/imangazaliev/didom/src/DiDom/Document.php:218
Stack trace:
#0 /root/91porn/vendor/imangazaliev/didom/src/DiDom/Document.php(69): DiDom\Document->load(false, false, 'html')
#1 /root/91porn/91all.php(15): DiDom\Document->__construct(false)
#2 /root/91porn/91all.php(35): listPage('http://627.work...', 1, 10)
#3 {main}
http://627.workarea7.live/v.php?category=top&viewtype=basic&page=5
InvalidArgumentException: DiDom\Document::load expects parameter 1 to be string, boolean given in /root/91porn/vendor/imangazaliev/didom/src/DiDom/Document.php:218
Stack trace:
#0 /root/91porn/vendor/imangazaliev/didom/src/DiDom/Document.php(69): DiDom\Document->load(false, false, 'html')
#1 /root/91porn/91all.php(15): DiDom\Document->__construct(false)
#2 /root/91porn/91all.php(35): listPage('http://627.work...', 1, 10)
#3 {main}
http://627.workarea7.live/v.php?category=top&viewtype=basic&page=6
InvalidArgumentException: DiDom\Document::load expects parameter 1 to be string, boolean given in /root/91porn/vendor/imangazaliev/didom/src/DiDom/Document.php:218
Stack trace:
#0 /root/91porn/vendor/imangazaliev/didom/src/DiDom/Document.php(69): DiDom\Document->load(false, false, 'html')
#1 /root/91porn/91all.php(15): DiDom\Document->__construct(false)
#2 /root/91porn/91all.php(35): listPage('http://627.work...', 1, 10)
#3 {main}
http://627.workarea7.live/v.php?category=top&viewtype=basic&page=7
InvalidArgumentException: DiDom\Document::load expects parameter 1 to be string, boolean given in /root/91porn/vendor/imangazaliev/didom/src/DiDom/Document.php:218
Stack trace:
#0 /root/91porn/vendor/imangazaliev/didom/src/DiDom/Document.php(69): DiDom\Document->load(false, false, 'html')
#1 /root/91porn/91all.php(15): DiDom\Document->__construct(false)
#2 /root/91porn/91all.php(35): listPage('http://627.work...', 1, 10)
#3 {main}
http://627.workarea7.live/v.php?category=top&viewtype=basic&page=8
InvalidArgumentException: DiDom\Document::load expects parameter 1 to be string, boolean given in /root/91porn/vendor/imangazaliev/didom/src/DiDom/Document.php:218
Stack trace:
#0 /root/91porn/vendor/imangazaliev/didom/src/DiDom/Document.php(69): DiDom\Document->load(false, false, 'html')
#1 /root/91porn/91all.php(15): DiDom\Document->__construct(false)
#2 /root/91porn/91all.php(35): listPage('http://627.work...', 1, 10)
#3 {main}
http://627.workarea7.live/v.php?category=top&viewtype=basic&page=9
InvalidArgumentException: DiDom\Document::load expects parameter 1 to be string, boolean given in /root/91porn/vendor/imangazaliev/didom/src/DiDom/Document.php:218
Stack trace:
#0 /root/91porn/vendor/imangazaliev/didom/src/DiDom/Document.php(69): DiDom\Document->load(false, false, 'html')
#1 /root/91porn/91all.php(15): DiDom\Document->__construct(false)
#2 /root/91porn/91all.php(35): listPage('http://627.work...', 1, 10)
#3 {main}
http://627.workarea7.live/v.php?category=top&viewtype=basic&page=10
InvalidArgumentException: DiDom\Document::load expects parameter 1 to be string, boolean given in /root/91porn/vendor/imangazaliev/didom/src/DiDom/Document.php:218
Stack trace:
#0 /root/91porn/vendor/imangazaliev/didom/src/DiDom/Document.php(69): DiDom\Document->load(false, false, 'html')
#1 /root/91porn/91all.php(15): DiDom\Document->__construct(false)
#2 /root/91porn/91all.php(35): listPage('http://627.work...', 1, 10)
#3 {main}
http://627.workarea7.live/v.php?category=mf&viewtype=basic&page=1
InvalidArgumentException: DiDom\Document::load expects parameter 1 to be string, boolean given in /root/91porn/vendor/imangazaliev/didom/src/DiDom/Document.php:218
Stack trace:
#0 /root/91porn/vendor/imangazaliev/didom/src/DiDom/Document.php(69): DiDom\Document->load(false, false, 'html')
#1 /root/91porn/91all.php(15): DiDom\Document->__construct(false)
#2 /root/91porn/91all.php(35): listPage('http://627.work...', 1, 5)
#3 {main}
http://627.workarea7.live/v.php?category=mf&viewtype=basic&page=2
InvalidArgumentException: DiDom\Document::load expects parameter 1 to be string, boolean given in /root/91porn/vendor/imangazaliev/didom/src/DiDom/Document.php:218
Stack trace:
#0 /root/91porn/vendor/imangazaliev/didom/src/DiDom/Document.php(69): DiDom\Document->load(false, false, 'html')
#1 /root/91porn/91all.php(15): DiDom\Document->__construct(false)
#2 /root/91porn/91all.php(35): listPage('http://627.work...', 1, 5)
#3 {main}
http://627.workarea7.live/v.php?category=mf&viewtype=basic&page=3
InvalidArgumentException: DiDom\Document::load expects parameter 1 to be string, boolean given in /root/91porn/vendor/imangazaliev/didom/src/DiDom/Document.php:218
Stack trace:
#0 /root/91porn/vendor/imangazaliev/didom/src/DiDom/Document.php(69): DiDom\Document->load(false, false, 'html')
#1 /root/91porn/91all.php(15): DiDom\Document->__construct(false)
#2 /root/91porn/91all.php(35): listPage('http://627.work...', 1, 5)
#3 {main}
http://627.workarea7.live/v.php?category=mf&viewtype=basic&page=4
InvalidArgumentException: DiDom\Document::load expects parameter 1 to be string, boolean given in /root/91porn/vendor/imangazaliev/didom/src/DiDom/Document.php:218
Stack trace:
#0 /root/91porn/vendor/imangazaliev/didom/src/DiDom/Document.php(69): DiDom\Document->load(false, false, 'html')
#1 /root/91porn/91all.php(15): DiDom\Document->__construct(false)
#2 /root/91porn/91all.php(35): listPage('http://627.work...', 1, 5)
#3 {main}
http://627.workarea7.live/v.php?category=mf&viewtype=basic&page=5
InvalidArgumentException: DiDom\Document::load expects parameter 1 to be string, boolean given in /root/91porn/vendor/imangazaliev/didom/src/DiDom/Document.php:218
Stack trace:
#0 /root/91porn/vendor/imangazaliev/didom/src/DiDom/Document.php(69): DiDom\Document->load(false, false, 'html')
#1 /root/91porn/91all.php(15): DiDom\Document->__construct(false)
#2 /root/91porn/91all.php(35): listPage('http://627.work...', 1, 5)
#3 {main}
http://627.workarea7.live/v.php?category=md&viewtype=basic&page=4
InvalidArgumentException: DiDom\Document::load expects parameter 1 to be string, boolean given in /root/91porn/vendor/imangazaliev/didom/src/DiDom/Document.php:218
Stack trace:
#0 /root/91porn/vendor/imangazaliev/didom/src/DiDom/Document.php(69): DiDom\Document->load(false, false, 'html')
#1 /root/91porn/91all.php(15): DiDom\Document->__construct(false)
#2 /root/91porn/91all.php(37): listPage('http://627.work...', 4, 4)

**Comment by leozvc** [comment]
91porn_php/detailPage.php
第14行 改为 $source = $page->first('#player_one source') 即可
