### ISSUE TITLE
node运行md5.js时报错

### ISSUE THREAD

**Issue by lvfoxx** [zzjzz9266a/91porn_php#64]
http://91porn.com/view_video.php?viewkey=63c0acd54ab2ed2b2fa4&page=10&viewtype=basic&category=top
/root/91porn_php/md5.js:1
(function (exports, require, module, __filename, __dirname) { <!DOCTYPE html>
SyntaxError: Unexpected token <
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
PHP Notice:  Undefined offset: 1 in /root/91porn_php/detailPage.php on line 83

**Comment by Chen-xc** [comment]
解密方式已经过时了吧.#player_one下面已经没有script了.
